version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db/db.sql :/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "library"
    networks:
      - dockerapi-dev

  syncfusion-library-management:
    image: syncfusion/try/library-management:1
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=library;username=postgres;password=postgres"
    networks:
      - dockerapi-dev  
  
volumes:
  db_volume: