create table if not exists public.books
(	
	bookId			INT				NOT NULL	PRIMARY KEY	GENERATED BY DEFAULT AS IDENTITY,
	bookName		varchar(255)	NOT NULL,
	authorName		varchar(250)	NULL,
	publishedYear 	INT 			NULL,
	Price 			NUMERIC(6,2) 	NULL,
	bookcategoryId 	INT 			NOT NULL,
	updatedOn 		DATE 			NOT NULL,
	IsDeleted 		BOOLEAN 		NOT NULL
);

create table if not exists public.bookcategories
(
	cateogoryId 	int   	not NULL PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY ,
	cateogoryName 	varchar(255) not NULL,
	updatedOn		Date	not NULL,
	IsDeleted 		boolean	not NULL 
	
);

insert into public.bookcategories (cateogoryid, cateogoryname, updatedon, isdeleted)
values 
	(1, 'IT', '2019/11/27', false),
	(2, 'Electronics', '2019/11/23', false),
	(3, 'Mechanical', '2019/11/22', false),
	(4, 'Civil', '2019/11/21', false),
	(5, 'Electricals', '2019/11/20', false),
	(6,	'Economics', '2019/11/02', true);

	
insert  into public.books (bookid, bookname, authorname, publishedyear, price, bookcategoryid, updatedon, isdeleted)
values 
	(1, 'C++', 'Balaguruswamy', 2001, 500, 1, '2019/11/27', false),
	(2, 'Microcontrollers', 'Mazidi', 2002, 550, 2, '2019/11/28', false),
	(3, 'Robotics', 'Sebastian', 2003, 600, 3, '2019/11/29', false),
	(4, 'Structural Engineering', 'Jacques Heyman', 2004, 800, 4, '2019/11/21', false),
	(5, 'DC Motors', 'Michael Faraday', 2004, 400, 5, '2019/11/01', false),
	(6, 'Economics', 'Nassim Nicholas', 2005, 300, 6, '2019/11/02', true),
	(7, 'Data Structure',null,null, 430,1,'2019/11/03', false),
	(8, 'Operating Systems', 'Abraham Silberschatz', 2007,null, 1, '2019/11/04', true),
	(9, 'Digital Electronics', 'William Gothmann',null ,null , 2,'2017/11/02', false);
	